import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  cardCor: {
    backgroundColor: "red",
    width: 80,
    height: 80,
    borderRadius: 10,
    marginRight: 10,
  },
  cardTamanho: {
    backgroundColor: "black",
    borderRadius: 10,
    marginRight: 10,
    width: 100,
    height: 40,
  },
  especificacao: {
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "space-between",
    borderColor: "#000",
    borderWidth: 2,
    padding: 10,
    flexDirection: "row",
    borderRadius: 10,
    marginBottom: 10,
  },
  descricao: {
    width: "100%",
    height: 150,
    alignItems: "center",
    justifyContent: "space-between",
    borderColor: "#000",
    borderWidth: 2,
    padding: 10,
    marginBottom: 10,
    flexDirection: "row",
    borderRadius: 10,
  },
  avaliacao: {
    width: "100%",
    height: 150,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "space-between",
    borderColor: "#000",
    borderWidth: 2,
    padding: 10,
    flexDirection: "row",
    borderRadius: 10,
  },
});

export default styles;
